sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: mr-ooops/mr-ooops.github.io
    target_branch: master
    email: mr-ooops@gmx.com
    name: mr-ooops
